[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html, php']

[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html, php']

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['css, sass']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css, sass']

[[plugins]]
repo = 'lilydjwg/colorizer'
on_ft = ['css']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'vim-scripts/fcitx.vim'
on_i = 1

[[plugins]]
repo = 'fuenor/im_control.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'w0rp/ale'
on_i = 1

[[plugins]]
repo = 'vim-scripts/AutoComplPop'
on_i = 1
